# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sudesh Sakthivel
title: Android Developer
email: sudeshim3@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: sudeshim3
github_username:  sudeshim3
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sudesh-sakthivel-0a3965122
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a android developer. I have experience of working on native apps for 3+ years in fast-paced startups. My key area of focus are writing clean, performant and testable code while ensuring
  to deliver great user experiance. Currently I am sharpening my skills on android devops and test automation.<br/><br/><br/> 
  <span style="font-size:150%">Skills</span> <br/>
  -  <mark>Architecture</mark>: (MVP, MVVM). Modular code with Test-driven development. <br/>
  -  <mark>Testing</mark>: Unit testing with Junit and Mockito and Instrumentation testing with Espresso. <br/>
  -  <mark>Library</mark>: Libraries provided by android architecture component, Dagger, RxJava, Coroutines, MpAndroidchart, Epoxy, SocketIO, ProtoBuf, etc. <br/>
  -  <mark>Android DevOps</mark>: CI/CD with Bitrise and Github actions. <br/>
  -  SDK development and artifact hosting. <br/>
  -  <mark>Game Development</mark>: Unity, Blender, Photoshop and various other game dev extensions. <br/>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience


# Education Section
# educaton_title: Education

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
